-- ============================================================================
--  V1__init.sql  —  Flyway migration #1 : the initial TaskFlow schema.
--
--  Creates three tables — users, categories, tasks — with their relationships,
--  constraints, and indexes. Flyway runs this exactly once and records it in the
--  flyway_schema_history table. Once it has run anywhere, it is FROZEN: future
--  changes go into V2__, V3__, ... never by editing this file.
--
--  Conventions used below:
--    • snake_case column names — Hibernate's default maps a Java field like
--      `displayName` to a column `display_name`, so our entities (Phase 3) will
--      line up with these names automatically.
--    • UUID primary keys (not auto-increment integers) — see the note on users.
--    • TIMESTAMPTZ for all moments in time — stores an absolute instant in UTC,
--      so behaviour is identical regardless of the server's local timezone.
-- ============================================================================


-- ============================ users =========================================
-- NOTE on the table name: we call it "users" (plural) NOT "user", because
-- `user` is a RESERVED keyword in PostgreSQL (SELECT user; returns the role).
-- Using the reserved word would force awkward quoting everywhere.
CREATE TABLE users (
    -- WHY UUID instead of a SERIAL/BIGINT auto-increment?
    --   1. The ID can be generated by the app BEFORE talking to the DB, which
    --      simplifies code and lets clients reference an entity immediately.
    --   2. IDs are not guessable/enumerable — you can't probe /users/1, /users/2.
    --   3. They're globally unique, so merging data across environments/shards
    --      never collides.
    -- gen_random_uuid() is built into PostgreSQL core (since v13), so no extension
    -- is needed. It's a DB-side safety net; the app will usually supply the UUID.
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Email is the login identity. We enforce uniqueness with a constraint below.
    -- (The service layer in Phase 5 will normalise emails to lowercase before
    --  saving, so "A@x.com" and "a@x.com" can't both register.)
    email          VARCHAR(255) NOT NULL,

    -- We store ONLY the BCrypt HASH of the password, never the password itself.
    -- A BCrypt hash is 60 characters; 100 leaves headroom for any algorithm prefix.
    password_hash  VARCHAR(100) NOT NULL,

    display_name   VARCHAR(100) NOT NULL,

    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- A named UNIQUE constraint. Naming it (uq_...) makes error messages and
    -- future migrations clearer than relying on Postgres's auto-generated name.
    CONSTRAINT uq_users_email UNIQUE (email)
);


-- ========================== categories ======================================
-- A category belongs to exactly one user (its owner). One user has many
-- categories — a classic one-to-many relationship, modelled by putting the
-- foreign key (owner_id) on the "many" side (here).
CREATE TABLE categories (
    id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name      VARCHAR(100) NOT NULL,
    color     VARCHAR(20),                      -- e.g. a hex code like '#3B82F6'; optional
    owner_id  UUID NOT NULL,

    -- FOREIGN KEY: guarantees owner_id always points to a real users.id row;
    -- the DB will reject an orphan category.
    -- ON DELETE CASCADE: if a user is deleted, their categories are deleted too.
    -- That's correct here — a category has no meaning without its owner.
    CONSTRAINT fk_categories_owner
        FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Index requested by the brief. Almost every query is "categories for THIS user"
-- (WHERE owner_id = ?). Without an index Postgres scans the whole table; with it,
-- it jumps straight to that user's rows.
CREATE INDEX idx_categories_owner_id ON categories (owner_id);


-- ============================= tasks ========================================
CREATE TABLE tasks (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title         VARCHAR(255) NOT NULL,
    description   TEXT,                          -- TEXT = unbounded length; good for free-form notes

    -- The status/priority enums. DESIGN DECISION: we store them as VARCHAR guarded
    -- by a CHECK constraint, rather than as a native PostgreSQL ENUM type. Why?
    --   • JPA/Hibernate maps a Java enum to a VARCHAR cleanly (@Enumerated(STRING)).
    --     Native PG enums need custom type handling and are fiddly to evolve.
    --   • Adding a new value to a native PG enum is a schema migration with quirks;
    --     with CHECK we just alter the constraint.
    -- The CHECK still gives us DB-level safety: an invalid value is rejected.
    status        VARCHAR(20)  NOT NULL DEFAULT 'TODO',
    priority      VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM',

    due_date      TIMESTAMPTZ,                   -- when the task is due (nullable)
    completed_at  TIMESTAMPTZ,                   -- set when marked DONE (nullable)

    owner_id      UUID NOT NULL,                 -- every task has an owner
    category_id   UUID,                          -- a task MAY belong to a category (nullable)

    -- Audit timestamps. The DB defaults are a backstop; JPA auditing (Phase 3)
    -- is the primary mechanism that keeps created_at/updated_at current.
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- Deleting a user removes all their tasks (CASCADE) — tasks can't outlive their owner.
    CONSTRAINT fk_tasks_owner
        FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,

    -- Deleting a CATEGORY does NOT delete the tasks in it; instead category_id is
    -- set to NULL (the task becomes "uncategorised"). ON DELETE SET NULL captures
    -- that intent — different from the owner relationship on purpose.
    CONSTRAINT fk_tasks_category
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,

    -- DB-level enforcement of the allowed enum values.
    CONSTRAINT chk_tasks_status   CHECK (status   IN ('TODO', 'IN_PROGRESS', 'DONE')),
    CONSTRAINT chk_tasks_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
);

-- COMPOSITE indexes requested by the brief. The column ORDER matters: an index on
-- (owner_id, status) efficiently serves "this user's tasks" AND "this user's tasks
-- with status = X", because owner_id is the leading column. The same logic applies
-- to (owner_id, due_date) for due-date filtering and sorting.
CREATE INDEX idx_tasks_owner_status   ON tasks (owner_id, status);
CREATE INDEX idx_tasks_owner_due_date ON tasks (owner_id, due_date);
